"use client";
import { useEffect, useState } from "react";
import { Mail, Phone, Search } from "lucide-react";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { sessionFetch } from "@/lib/api-client";

type Enquiry = { id:string; name:string; email:string; phone:string; projectType:string; budgetRange:string; message:string; status:string; createdAt:string };
export default function EnquiriesPage() {
  const [items,setItems]=useState<Enquiry[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState("");
  useEffect(()=>{ sessionFetch("/api/v1/enquiries").then(async r=>{if(!r.ok) throw new Error("Unable to load enquiries"); return r.json()}).then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false)); },[]);
  const filtered=items.filter(x=>`${x.name} ${x.email} ${x.projectType}`.toLowerCase().includes(search.toLowerCase()));
  return <DashboardShell><div className="mx-auto max-w-7xl"><div className="mb-7"><p className="text-[9px] font-bold uppercase tracking-[.25em] text-blue-300/60">Lead pipeline</p><h1 className="mt-2 text-3xl font-black">Project enquiries</h1><p className="mt-2 text-sm text-white/35">Website requests arrive here as real PostgreSQL records.</p></div><div className="mb-4 relative max-w-xl"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/30"/><input className="glass-input pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email or project type…"/></div>{error&&<p className="mb-4 rounded-xl bg-red-500/10 p-3 text-xs text-red-200">{error}</p>}<div className="space-y-3">{loading?Array.from({length:3}).map((_,i)=><div key={i} className="h-28 animate-pulse rounded-3xl bg-white/5"/>):filtered.length===0?<div className="rounded-3xl border border-white/8 bg-white/[.025] p-10 text-center text-sm text-white/35">No enquiries found.</div>:filtered.map(item=><article key={item.id} className="rounded-3xl border border-white/8 bg-white/[.025] p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold">{item.name}</h2><span className="rounded-full border border-blue-300/10 bg-blue-500/10 px-2 py-1 text-[8px] font-bold uppercase tracking-[.15em] text-blue-200">{item.status}</span></div><p className="mt-2 text-xs text-white/45">{item.projectType} · {item.budgetRange}</p><p className="mt-3 max-w-3xl text-sm leading-6 text-white/55">{item.message}</p></div><div className="shrink-0 text-xs text-white/40"><a className="flex items-center gap-2 hover:text-white" href={`mailto:${item.email}`}><Mail size={13}/>{item.email}</a><a className="mt-2 flex items-center gap-2 hover:text-white" href={`tel:${item.phone}`}><Phone size={13}/>{item.phone}</a><p className="mt-2 text-[9px] uppercase tracking-[.12em]">{new Date(item.createdAt).toLocaleString()}</p></div></div></article>)}</div></div></DashboardShell>;
}
